// Single source of truth for which backend actually generates responses.
// The in-app model picker selects assistant personas (system-prompt style);
// it does not route to different providers.
export const BACKEND_MODEL = 'gemini-flash-latest';

export const PERSONA_NOTE =
  `Personas change tone and style only. All responses are generated by ${BACKEND_MODEL}.`;
