import { AIService } from '../types/service';

export const INITIAL_SERVICES: AIService[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    displayUrl: 'chatgpt.com',
    description: 'OpenAI GPT-4o, reasoning models & projects',
    color: '#10A37F',
    iconKey: 'bot',
    isDefault: true,
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    displayUrl: 'claude.ai',
    description: 'Anthropic Claude 3.5 Sonnet, Artifacts & Projects',
    color: '#DA7756',
    iconKey: 'sparkles',
    isDefault: true,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    url: 'https://gemini.google.com',
    displayUrl: 'gemini.google.com',
    description: 'Gemini 2.5 Flash, 2.0 Pro & Deep Research',
    color: '#3B82F6',
    iconKey: 'gemini',
    isDefault: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    displayUrl: 'perplexity.ai',
    description: 'Live web search with citations & Pro research',
    color: '#22C55E',
    iconKey: 'search',
    isDefault: true,
  },
  {
    id: 'grok',
    name: 'Grok',
    url: 'https://grok.com',
    displayUrl: 'grok.com',
    description: 'xAI Grok 2 & Grok 3 with real-time X knowledge',
    color: '#E5E7EB',
    iconKey: 'zap',
    isDefault: true,
  },
];

export const POPULAR_PRESETS: Omit<AIService, 'id'>[] = [
  {
    name: 'DeepSeek Chat',
    url: 'https://chat.deepseek.com',
    displayUrl: 'chat.deepseek.com',
    description: 'DeepSeek V3 & R1 reasoning models',
    color: '#0284C7',
    iconKey: 'brain',
  },
  {
    name: 'Mistral Le Chat',
    url: 'https://chat.mistral.ai',
    displayUrl: 'chat.mistral.ai',
    description: 'Mistral Large 2, Pixtral & Le Chat canvas',
    color: '#F97316',
    iconKey: 'flame',
  },
  {
    name: 'Microsoft Copilot',
    url: 'https://copilot.microsoft.com',
    displayUrl: 'copilot.microsoft.com',
    description: 'Microsoft Copilot & Bing web grounding',
    color: '#0EA5E9',
    iconKey: 'cpu',
  },
  {
    name: 'Google NotebookLM',
    url: 'https://notebooklm.google.com',
    displayUrl: 'notebooklm.google.com',
    description: 'Grounded notebook research & Audio Overviews',
    color: '#8B5CF6',
    iconKey: 'book',
  },
  {
    name: 'Poe by Quora',
    url: 'https://poe.com',
    displayUrl: 'poe.com',
    description: 'Multi-bot conversation ecosystem',
    color: '#EC4899',
    iconKey: 'message-square',
  },
  {
    name: 'v0 by Vercel',
    url: 'https://v0.dev',
    displayUrl: 'v0.dev',
    description: 'Generative UI and React component builder',
    color: '#FFFFFF',
    iconKey: 'code',
  },
];
