import { MCPConnector } from '../types/chat';

export const DEFAULT_MCP_CONNECTORS: MCPConnector[] = [
  {
    id: 'github',
    name: 'GitHub MCP Server',
    description: 'Inspect repositories, search codebase, read issues and review pull requests.',
    icon: 'github',
    category: 'developer',
    transport: 'stdio',
    commandOrUrl: 'npx -y @modelcontextprotocol/server-github',
    isConnected: true,
    isEnabledForChat: true,
    tools: [
      { name: 'search_repositories', description: 'Search GitHub repositories for code or topics' },
      { name: 'read_file_contents', description: 'Read files directly from GitHub repos and branches' },
      { name: 'list_pull_requests', description: 'List open pull requests and code reviews' },
    ],
  },
  {
    id: 'filesystem',
    name: 'Local Filesystem MCP',
    description: 'Access local directory trees, read code files, analyze projects and write files securely.',
    icon: 'folder',
    category: 'filesystem',
    transport: 'stdio',
    commandOrUrl: 'npx -y @modelcontextprotocol/server-filesystem /Users/developer/Projects',
    isConnected: true,
    isEnabledForChat: true,
    tools: [
      { name: 'read_file', description: 'Read contents of a file at specified path' },
      { name: 'write_file', description: 'Create or overwrite files with new contents' },
      { name: 'list_directory', description: 'List files and directories with metadata' },
      { name: 'search_files', description: 'Search recursively matching glob patterns' },
    ],
  },
  {
    id: 'code_interpreter',
    name: 'Codex Code Interpreter',
    description: 'Execute Python, TypeScript, and shell scripts in an isolated sandbox with chart generation.',
    icon: 'terminal',
    category: 'developer',
    transport: 'builtin',
    commandOrUrl: 'builtin:codex-sandbox-v2',
    isConnected: true,
    isEnabledForChat: true,
    tools: [
      { name: 'execute_python', description: 'Run Python code with numpy, pandas, matplotlib, sympy' },
      { name: 'execute_javascript', description: 'Evaluate Node.js / JavaScript logic and algorithms' },
    ],
  },
  {
    id: 'web_search',
    name: 'Brave & Web Search Plugin',
    description: 'Live web search with fresh real-time web citations, developer documentation, and news.',
    icon: 'globe',
    category: 'search',
    transport: 'sse',
    commandOrUrl: 'https://api.search.brave.com/res/v1/web/search',
    isConnected: true,
    isEnabledForChat: true,
    tools: [
      { name: 'web_search', description: 'Execute real-time web queries and extract citations' },
      { name: 'fetch_webpage', description: 'Scrape and clean full text of online articles and docs' },
    ],
  },
  {
    id: 'postgres',
    name: 'PostgreSQL Database MCP',
    description: 'Connect to Postgres/Neon/Supabase databases, inspect schemas, and query relational tables.',
    icon: 'database',
    category: 'database',
    transport: 'stdio',
    commandOrUrl: 'npx -y @modelcontextprotocol/server-postgres postgresql://user:pass@localhost:5432/db',
    isConnected: false,
    isEnabledForChat: false,
    tools: [
      { name: 'describe_tables', description: 'Inspect schema columns and foreign keys' },
      { name: 'execute_readonly_query', description: 'Run SQL SELECT queries with pagination' },
    ],
  },
  {
    id: 'gdrive',
    name: 'Google Drive MCP Connector',
    description: 'Search, read, and summarize Google Docs, Spreadsheets, and Drive folders.',
    icon: 'file-text',
    category: 'productivity',
    transport: 'sse',
    commandOrUrl: 'https://mcp.workspace.google.com/sse',
    isConnected: false,
    isEnabledForChat: false,
    tools: [
      { name: 'search_drive', description: 'Search Google Drive for files and documents' },
      { name: 'read_doc_text', description: 'Read document paragraphs and sheet tabular data' },
    ],
  },
];
